-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rescue_id bigint NOT NULL,
    id_user bigint NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hitories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    create_at date,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    update_at date,
    post_id bigint NOT NULL,
    rescue_team_id bigint NOT NULL,
    CONSTRAINT hitories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content text COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp(6) without time zone NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_receiver bigint NOT NULL,
    id_sender bigint NOT NULL,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content character varying(255) COLLATE pg_catalog."default",
    create_at date,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.places
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    latitude double precision NOT NULL,
    longtude double precision NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT places_pkey PRIMARY KEY (id),
    CONSTRAINT ukb483kdkc9d0vv1m60vy7x2wfd UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.posts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content character varying(255) COLLATE pg_catalog."default",
    create_at date,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    update_at date,
    id_place bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT posts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.relatives
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    relationship character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_parent bigint NOT NULL,
    id_user bigint NOT NULL,
    CONSTRAINT relatives_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rescue_teams
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_place bigint NOT NULL,
    post_id bigint NOT NULL,
    CONSTRAINT rescue_teams_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    create_at date,
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_changed_at date,
    phone_number character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    update_at date,
    id_place bigint,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number),
    CONSTRAINT ukchvoee79risgbxtj5525qlolf UNIQUE (id_place)
);

ALTER TABLE IF EXISTS public.groups
    ADD CONSTRAINT fk936qkwm0ubc1e9w0de4vtncma FOREIGN KEY (rescue_id)
    REFERENCES public.rescue_teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.groups
    ADD CONSTRAINT fk9wxsmnk99stttx2h70ps75qyk FOREIGN KEY (id_user)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hitories
    ADD CONSTRAINT fk1gstp83m15n2j7i0iywetkc38 FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hitories
    ADD CONSTRAINT fkjakdgl5ux55coi4jxie74xb1f FOREIGN KEY (rescue_team_id)
    REFERENCES public.rescue_teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fk3nwahn9plcioqsad6fbidro7m FOREIGN KEY (id_sender)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fkps8gktakk146d49w62epmhygt FOREIGN KEY (id_receiver)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.places
    ADD CONSTRAINT fkqmg0l98kpihrma9jr4hx0x22b FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukb483kdkc9d0vv1m60vy7x2wfd
    ON public.places(user_id);


ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT fk5lidm6cqbc7u4xhqpxm898qme FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT fkbjixy7ti1g1vf1nboxgkry5p FOREIGN KEY (id_place)
    REFERENCES public.places (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relatives
    ADD CONSTRAINT fkd4w546pjj81a4cskpuee2xtni FOREIGN KEY (id_parent)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.relatives
    ADD CONSTRAINT fkg9u4v9w175hlkq7v0ijbq7i64 FOREIGN KEY (id_user)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rescue_teams
    ADD CONSTRAINT fkn4tlwdg3tuu3pei9o68pb6mq7 FOREIGN KEY (id_place)
    REFERENCES public.places (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rescue_teams
    ADD CONSTRAINT fkw25rcihc2ua1am7alpk8j6kb FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fkhv4s83eam3uo2owi2qgut2btj FOREIGN KEY (id_place)
    REFERENCES public.places (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukchvoee79risgbxtj5525qlolf
    ON public.users(id_place);

END;